name: Release Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Add helm repositories
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

      - name: Update chart dependencies
        run: |
          for chart in charts/*/; do
            if [ -f "$chart/Chart.yaml" ]; then
              echo "Updating dependencies for $chart"
              helm dependency update "$chart"
            fi
          done

      - name: Package Helm charts
        run: |
          mkdir -p .deploy
          for chart in charts/*/; do
            if [ -f "$chart/Chart.yaml" ]; then
              echo "Packaging $chart"
              helm package "$chart" -d .deploy
            fi
          done

      - name: Checkout gh-pages branch
        run: |
          git fetch origin gh-pages:gh-pages || true
          if git show-ref --verify --quiet refs/heads/gh-pages; then
            echo "gh-pages branch exists"
            git worktree add gh-pages-deploy gh-pages
          else
            echo "Creating gh-pages branch"
            git worktree add --detach gh-pages-deploy
            cd gh-pages-deploy
            git checkout --orphan gh-pages
            git rm -rf . || true
            touch index.yaml
            echo "# Homelab Packages Helm Repository" > README.md
            git add .
            git commit -m "Initialize gh-pages branch"
            cd ..
          fi

      - name: Update Helm repository index
        run: |
          if [ -f "gh-pages-deploy/index.yaml" ]; then
            helm repo index .deploy --url https://${{ github.repository_owner }}.github.io/homelab-packages --merge gh-pages-deploy/index.yaml
          else
            helm repo index .deploy --url https://${{ github.repository_owner }}.github.io/homelab-packages
          fi
          cp .deploy/* gh-pages-deploy/ || true
          
      - name: Push to gh-pages
        working-directory: ./gh-pages-deploy
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update Helm repository with charts from ${{ github.sha }}"
            git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" gh-pages
          fi