name: Release Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.13.0'
          token: ${{ github.token }}

      - name: Add helm repositories
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

      - name: Update chart dependencies
        run: |
          for chart in charts/*/; do
            if [ -f "$chart/Chart.yaml" ]; then
              echo "Updating dependencies for $chart"
              helm dependency update "$chart"
            fi
          done

      - name: Package Helm charts
        run: |
          mkdir -p .deploy
          for chart in charts/*/; do
            if [ -f "$chart/Chart.yaml" ]; then
              echo "Packaging $chart"
              helm package "$chart" -d .deploy
            fi
          done
          ls -la .deploy/

      - name: Checkout gh-pages branch
        run: |
          git fetch origin gh-pages:refs/remotes/origin/gh-pages || echo "No gh-pages branch yet"
          if git show-ref --verify --quiet refs/remotes/origin/gh-pages; then
            echo "gh-pages branch exists remotely"
            git checkout --track origin/gh-pages
          else
            echo "Creating new gh-pages branch"
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "Initialize gh-pages branch"
          fi

      - name: Update Helm repository index
        run: |
          # Copy packaged charts to current directory
          cp .deploy/*.tgz . 2>/dev/null || true
          
          # Generate or update the index
          if [ -f "index.yaml" ]; then
            echo "Updating existing index.yaml"
            helm repo index . --url https://orbli.github.io/homelab-packages --merge index.yaml
          else
            echo "Creating new index.yaml"
            helm repo index . --url https://orbli.github.io/homelab-packages
          fi
          
          # Create a simple README if it doesn't exist
          if [ ! -f "README.md" ]; then
            echo "# Homelab Packages Helm Repository" > README.md
            echo "" >> README.md
            echo "## Usage" >> README.md
            echo '```bash' >> README.md
            echo "helm repo add homelab-packages https://orbli.github.io/homelab-packages" >> README.md
            echo "helm repo update" >> README.md
            echo "helm search repo homelab-packages" >> README.md
            echo '```' >> README.md
          fi
          
      - name: Commit and push to gh-pages
        run: |
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update Helm repository with charts from ${{ github.sha }}"
            git push origin gh-pages
          fi