name: Release NPM Packages

on:
  push:
    tags:
      - 'nodejs-*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Get package name from tag
        id: tag
        run: |
          echo "package=${GITHUB_REF#refs/tags/nodejs-}" >> $GITHUB_OUTPUT
      
      - name: Publish to NPM
        run: |
          cd nodejs/${{ steps.tag.outputs.package }}
          npm ci
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}