name: Release Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Add helm repositories
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

      - name: Update chart dependencies
        run: |
          for chart in charts/*/; do
            if [ -f "$chart/Chart.yaml" ]; then
              echo "Updating dependencies for $chart"
              helm dependency update "$chart"
            fi
          done

      - name: Package Helm charts
        run: |
          mkdir -p .deploy
          for chart in charts/*/; do
            if [ -f "$chart/Chart.yaml" ]; then
              echo "Packaging $chart"
              helm package "$chart" -d .deploy
            fi
          done

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
        continue-on-error: true

      - name: Create gh-pages branch if needed
        if: failure()
        run: |
          mkdir -p gh-pages
          cd gh-pages
          git init
          git remote add origin https://github.com/${{ github.repository }}.git
          git checkout -b gh-pages
          cd ..

      - name: Update Helm repository index
        run: |
          if [ -f "gh-pages/index.yaml" ]; then
            helm repo index .deploy --url https://${{ github.repository_owner }}.github.io/homelab-packages --merge gh-pages/index.yaml
          else
            helm repo index .deploy --url https://${{ github.repository_owner }}.github.io/homelab-packages
          fi
          cp .deploy/* gh-pages/ || true
          
      - name: Push to gh-pages
        working-directory: ./gh-pages
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git config user.name "$GITHUB_ACTOR"
            git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git commit -m "Update Helm repository with charts from ${{ github.sha }}"
            git push origin gh-pages --force
          fi